# Generated by Django 5.2.5 on 2025-09-20 07:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('creativity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('leadership', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('teamwork', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('communication', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('problem_solving', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='Profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')])),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Completed'), (3, 'Expired')])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Profiles.profile')),
            ],
        ),
    ]
